### PR TITLE
fix(ui): Show container images in dashboard for rollouts with a WorkloadRef

### LINKED ISSUE #1525: Rollouts Dashboard doesn't fully support using workloadRef
## Summary 

When using a `Rollout` which uses `workloadRef`:
- the "Containers" section is not populated (it just says "Add more containers to fill this space")
- the "Rollback" buttons on previous revisions don't work -- clicking them doesn't do anything

I think either those features should be removed when using `workloadRef`, or they should be updated to work.

## Diagnostics

What version of Argo Rollouts are you running?

Recent master build

---

**Message from the maintainers**:

Impacted by this bug? Give it a 👍. We prioritize the issues with the most 👍.

### PR DESCRIPTION
**Pull request by rbreeze**
Fixes #1525 

Signed-off-by: Remington Breeze <remington@breeze.software>

Checklist:

* [ ] Either (a) I've created an [enhancement proposal](https://github.com/argoproj/argo-rollouts/issues/new/choose) and discussed it with the community, (b) this is a bug fix, or (c) this is a chore.
* [ ] The title of the PR is (a) [conventional](https://www.conventionalcommits.org/en/v1.0.0/), (b) states what changed, and (c) suffixes the related issues number. E.g. `"fix(controller): Updates such and such. Fixes #1234"`.  
* [ ] I've signed my commits with [DCO](https://github.com/argoproj/argoproj)
* [ ] I have written unit and/or e2e tests for my change. PRs without these are unlikely to be merged.
* [ ] My builds are green. Try syncing with master if they are not. 
* [ ] My organization is added to [USERS.md](https://github.com/argoproj/argo-rollouts/blob/master/USERS.md).

### CODE REVIEW

File: pkg/kubectl-argo-rollouts/info/rollout_info.go [hunk 1]
```diff
@@ -75,11 +76,21 @@ func NewRolloutInfo(
...
+		}
+	} else {
+		for c := range ro.Spec.Template.Spec.Containers {
+			curContainer := ro.Spec.Template.Spec.Containers[c]
+			roInfo.Containers = append(roInfo.Containers, &rollout.ContainerInfo{Name: curContainer.Name, Image: curContainer.Image})
+		}
 	}
 
+	
+
```
Comment (huikang) [inline pkg/kubectl-argo-rollouts/info/rollout_info.go:93]: nit: remove extract space

File: pkg/kubectl-argo-rollouts/info/rollout_info.go [hunk 2]
```diff
@@ -75,11 +76,21 @@ func NewRolloutInfo(
...
+	if workloadRef != nil {
+		for c := range workloadRef.Spec.Template.Spec.Containers {
+			curContainer := workloadRef.Spec.Template.Spec.Containers[c]
+			roInfo.Containers = append(roInfo.Containers, &rollout.ContainerInfo{Name: curContainer.Name, Image: curContainer.Image})
+		}
+	} else {
+		for c := range ro.Spec.Template.Spec.Containers {
+			curContainer := ro.Spec.Template.Spec.Containers[c]
+			roInfo.Containers = append(roInfo.Containers, &rollout.ContainerInfo{Name: curContainer.Name, Image: curContainer.Image})
+		}
```
Comment (huikang) [inline pkg/kubectl-argo-rollouts/info/rollout_info.go:89]: I guess we can improve the code by

```
var containerList []corev1.container
if workloadRef != nil {
    containerList = workloadRef.Spec.Template.Spec.Containers
} else {
    containerList = ro.Spec.Template.Spec.Containers
}

for _, c := range ro.Spec.Template.Spec.Containers {
	roInfo.Containers = append(roInfo.Containers, &rollout.ContainerInfo{Name: c.Name, Image: c.Image})
}
```

Comment (rbreeze) [reply pkg/kubectl-argo-rollouts/info/rollout_info.go:89]: Ah, I did try this, but then there is a panic at `for _, c := range ro.Spec.Template.Spec.Containers {` if using a workloadRef, because the rollout has no containers.

I also considered setting a "workload" variable to either the rollout or deployment depending on if using workloadRef, but the issue there is they are not the same type.

Comment (huikang) [reply pkg/kubectl-argo-rollouts/info/rollout_info.go:89]: My mistake. The for loop should be `for _, c := range containerList {`. WDYT?

Comment (rbreeze) [reply pkg/kubectl-argo-rollouts/info/rollout_info.go:89]: Ah I see good suggestion, changing now! Thanks

**Review by jessesuen — APPROVED** [review]
LGTM!
