### PR TITLE
fix: create analysisrun cmd using template generated name

### LINKED ISSUE #1473: command  create analysisrun fails to create analysisrun
## Summary 

What happened/what you expected to happen?

```
kubectl apply -f ./pkg/kubectl-argo-rollouts/cmd/create/testdata/analysis-template.yaml   
kubectl-argo-rollouts-darwin-amd64 create analysisrun  --from pass  -a foo=bar  --name test
```

1. Analysisrun can't be create due to the existing resourceVersion field

```
Error: resourceVersion should not be set on objects to be created
```

2. Spec.args are not resolved correctly even argument is provided in the command.

```
nable to resolve metric arguments: argument \"foo\" was not supplied" analysisrun=test namespace=default
```

## Diagnostics

What version of Argo Rollouts are you running?

master

```
# Paste the logs from the rollout controller

# Logs for the entire controller:
kubectl logs -n argo-rollouts deployment/argo-rollouts

# Logs for a specific rollout:
kubectl logs -n argo-rollouts deployment/argo-rollouts | grep rollout=<ROLLOUTNAME>
```

---

**Message from the maintainers**:

Impacted by this bug? Give it a 👍. We prioritize the issues with the most 👍.

### PR DESCRIPTION
**Pull request by huikang**
- set templateName if analsysit template has name in metadata
- remove resourceVersion and fix spec.args 

Signed-off-by: Hui Kang <hui.kang@salesforce.com>

fix #1473 

Checklist:

* [ ] Either (a) I've created an [enhancement proposal](https://github.com/argoproj/argo-rollouts/issues/new/choose) and discussed it with the community, (b) this is a bug fix, or (c) this is a chore.
* [ ] The title of the PR is (a) [conventional](https://www.conventionalcommits.org/en/v1.0.0/), (b) states what changed, and (c) suffixes the related issues number. E.g. `"fix(controller): Updates such and such. Fixes #1234"`.  
* [ ] I've signed my commits with [DCO](https://github.com/argoproj/argoproj)
* [ ] I have written unit and/or e2e tests for my change. PRs without these are unlikely to be merged.
* [ ] My builds are green. Try syncing with master if they are not. 
* [ ] My organization is added to [USERS.md](https://github.com/argoproj/argo-rollouts/blob/master/USERS.md).

### CODE REVIEW

File: pkg/kubectl-argo-rollouts/cmd/create/create.go [hunk 1]
```diff
@@ -274,11 +274,11 @@ func NewCmdCreateAnalysisRun(o *options.ArgoRolloutsOptions) *cobra.Command {
 				}
 			}
 
-			objName, notFound, err := unstructured.NestedString(obj.Object, "metadata", "name")
+			objName, found, err := unstructured.NestedString(obj.Object, "metadata", "name")
 			if err != nil {
 				return err
 			}
-			if !notFound {
+			if found {
```
Comment (jessesuen) [inline pkg/kubectl-argo-rollouts/cmd/create/create.go:281]: oops!

File: utils/analysis/helpers.go [hunk 2]
```diff
@@ -373,7 +372,17 @@ func NewAnalysisRunFromUnstructured(obj *unstructured.Unstructured, templateArgs
 		return nil, err
 	}
 
+	// Remove resourceVersion if exists
+	_, found, err := unstructured.NestedString(obj.Object, "metadata", "resourceVersion")
```
Comment (jessesuen) [inline utils/analysis/helpers.go:376]: Does this fix imply we never had `--from in-cluster-analysis-template` working properly?

**Review by jessesuen — APPROVED** [review]

File: utils/analysis/helpers.go (hunk 2 above)
Comment (huikang) [reply utils/analysis/helpers.go:376]: yeah, the unit test failed to catch that because of the fake client.
