### PR TITLE
fix: missing fields in destinationrule

### LINKED ISSUE #1238: Istio DestinationRule subset trafficPolicy lost
## Summary 

When using Argo Rollouts' new Istio DestinationRule subset support, the subset's trafficPolicy is lost during the update.

I believe this is due to an incomplete copy of the structure of Istio's DestinationRule Subset struct. The problematic code is: https://github.com/argoproj/argo-rollouts/blob/master/rollout/trafficrouting/istio/istio_types.go#L47-L50

## Diagnostics

Argo Rollouts 1.0.1

---

**Message from the maintainers**:

Impacted by this bug? Give it a 👍. We prioritize the issues with the most 👍.

### PR DESCRIPTION
**Pull request by huikang**
- add Extra to DestinationRule to hold any other fields from istio's
  destinationRule
- handle any extra fields that could be introduced to the subsets
  in istio's destinationRule fields
- unit test added

Signed-off-by: Hui Kang <hui.kang@salesforce.com>

close #1238 

Checklist:

* [x] Either (a) I've created an [enhancement proposal](https://github.com/argoproj/argo-rollouts/issues/new/choose) and discussed it with the community, (b) this is a bug fix, or (c) this is a chore.
* [x] The title of the PR is (a) [conventional](https://www.conventionalcommits.org/en/v1.0.0/), (b) states what changed, and (c) suffixes the related issues number. E.g. `"fix(controller): Updates such and such. Fixes #1234"`.  
* [x] I've signed my commits with [DCO](https://github.com/argoproj/argoproj)
* [x] I have written unit and/or e2e tests for my change. PRs without these are unlikely to be merged.
* [x] My builds are green. Try syncing with master if they are not. 
* [x] My organization is added to [USERS.md](https://github.com/argoproj/argo-rollouts/blob/master/USERS.md).

### CODE REVIEW

**Comment by huikang** [comment]
@jessesuen , please take a look at this PR when you have time. The approach is tedious as we can not predict the key names of the additional fields in the subets. Do you have any better idea? Thanks.

File: rollout/trafficrouting/istio/istio_test.go [hunk 1]
```diff
@@ -391,6 +392,52 @@ func rolloutWithDestinationRule() *v1alpha1.Rollout {
...
+spec:
+  subsets:
+  - name: stable
+    labels:
+      version: v3
+  - name: canary
+    trafficPolicy:
+      loadBalancer:
+        simple: ROUND_ROBIN
+`)
```
Comment (jessesuen) [inline rollout/trafficrouting/istio/istio_test.go:413]: Can we improve the test to verify we also preserve fields at the `.spec.XXX` level? For example, this example from istio docs which has `spec.host` and `spec.trafficPolicy`:

```yaml
apiVersion: networking.istio.io/v1beta1
kind: DestinationRule
metadata:
  name: bookinfo-ratings
spec:
  host: ratings.prod.svc.cluster.local
  trafficPolicy:
    loadBalancer:
      simple: LEAST_CONN
  subsets:
  - name: testversion
    labels:
      version: v3
    trafficPolicy:
      loadBalancer:
        simple: ROUND_ROBIN
```

File: rollout/trafficrouting/istio/istio.go [hunk 2]
```diff
@@ -224,15 +225,49 @@ func (r *Reconciler) UpdateHash(canaryHash, stableHash string) error {
...
+		newsubset["name"] = subset.Name
+		newsubset["labels"] = subset.Labels
+
+		if subset.Extra == nil {
+			subsets = append(subsets, newsubset)
+			continue
+		}
+
+		extra := map[string]interface{}{}
+		inputbyte, _ := json.Marshal(dRule.Spec.Subsets[1].Extra)
```
[the remark this answers is not in the document]
Comment (huikang) [reply rollout/trafficrouting/istio/istio.go]: Fixed. Thanks.

File: rollout/trafficrouting/istio/istio_test.go (hunk 1 above)
Comment (huikang) [reply rollout/trafficrouting/istio/istio_test.go:413]: Sure. Let me update the PR to generalize the method to the `.spec`.

Comment (huikang) [reply rollout/trafficrouting/istio/istio_test.go:413]: @jessesuen , I think the current implement has been able to preserve the fields of `.spec.XXX`. Following is a snippet of a destination rule after an update to a rollout.

```
spec:
  host: istio-rollout                                                <--------- Preserved
  subsets:
  - labels:
      app: istio-rollout
      rollouts-pod-template-hash: 6646844db8
    name: canary
  - labels:
      app: istio-rollout
      rollouts-pod-template-hash: cf89dfb88
    name: stable
    trafficPolicy:                                                      <--------- Preserved by the PR
      loadBalancer:
        simple: ROUND_ROBIN
  trafficPolicy:                                                         <--------- Preserved
    loadBalancer:
      simple: LEAST_CONN
```

However, I could not find the relevant part in the code. Do you have any idea?

Comment (huikang) [reply rollout/trafficrouting/istio/istio_test.go]: So to verify we preserve the fields under `.spec`, I added a string comparison between the expected result and the unstructured object.

**Review by jessesuen — APPROVED** [review]

**Comment by jessesuen** [comment]
Thank you!
