### PR TITLE
fix: rollout paused longer than progressDeadlineSeconds would briefly degrade

### LINKED ISSUE #1225: status command exits before timout
## Summary 

I have a rollout that was being watched via `status` with a `--timeout=3h` flag.  It exited with a `degraded` after 20 minutes.

## Diagnostics

What version of Argo Rollouts are you running?  v1.0.1 (kubectl-argo-rollouts = v1.0.0)

```
2021-05-27 14:13:33 EDT Status: Downloaded newer image for gcr.io/helpful-cat-109717/kubectl-argo-rollouts:v1.0.0
2021-05-27 14:13:34 EDT Executing command: kubectl get deployment -l "app.kubernetes.io/name=managed-satellite-envoy" -o name | cut -d '/' -f 2 | xargs -n 1 kubectl-argo-rollouts status --timeout=3h
2021-05-27 14:33:51 EDT Error: The rollout is in a degraded state with message: ProgressDeadlineExceeded: ReplicaSet "public-satellite-pools-managed-satellite-envoy-v2-6f9df7c4bf" has timed out progressing.
```

14:13 is when helm pushed the change.
14:33 is when the command failed.

The rollout itself completed successfully shortly thereafter. 

(there is only one rollout returned by the first kubectl, and I've omitted the extra flags to kubectl for brevity)

```
# Paste the logs from the rollout controller

Logs attached. The server doesn't show any errors.  Possibly this is a client bug. I've seen this happen twice now.  Is there anything else I can provide to help here?

# Logs for the entire controller:
kubectl logs -n argo-rollouts depl
[filtered2.csv](https://github.com/argoproj/argo-rollouts/files/6556579/filtered2.csv)
oyment/argo-rollouts

# Logs for a specific rollout:
kubectl logs -n argo-rollouts deployment/argo-rollouts | grep rollout=<ROLLOUTNAME>
```

---

**Message from the maintainers**:

Impacted by this bug? Give it a 👍. We prioritize the issues with the most 👍.

### PR DESCRIPTION
**Pull request by khhirani**
Closes #1225

Signed-off-by: khhirani <kareena.hirani@gmail.com>

### CODE REVIEW

File: rollout/sync.go [hunk 1]
```diff
@@ -657,7 +660,7 @@ func (c *rolloutContext) calculateRolloutConditions(newStatus v1alpha1.RolloutSt
 			if c.newRS != nil {
 				msg = fmt.Sprintf(conditions.ReplicaSetTimeOutMessage, c.newRS.Name)
 			}
-			condition := conditions.NewRolloutCondition(v1alpha1.RolloutProgressing, corev1.ConditionFalse, conditions.TimedOutReason, msg)
+			condition := conditions.NewRolloutCondition(v1alpha1.RolloutProgressing, corev1.ConditionTrue, conditions.TimedOutReason, msg)
```
Comment (jessesuen) [inline rollout/sync.go:663]: If we are timed out, why do we set Progressing condition to be True?

**Comment by jessesuen** [comment]
The e2e tests are failing because the github environment doesn't have the kubectl argo rollouts plugin installed.

```
Error: unknown command "argo" for "kubectl"
Run 'kubectl --help' for usage.
```

So you'll need to invoke the plugin logic another way. You can follow how I use the Promote() logic of the plugin from the e2e tests.

File: rollout/controller_test.go [hunk 2]
```diff
@@ -965,6 +965,25 @@ func (f *fixture) getPatchedRollout(index int) string {
...
+	action := filterInformerActions(f.client.Actions())[index]
+	patchAction, ok := action.(core.PatchAction)
+	if !ok {
+		f.t.Fatalf("Expected Patch action, not %s", action.GetVerb())
+	}
+	ro := make(map[string]interface{})
+	err := json.Unmarshal(patchAction.GetPatch(), &ro)
+	if err != nil {
+		return "", err
+	}
```
Comment (jessesuen) [inline rollout/controller_test.go:978]: Let's simplify this method signature such that it doesn't ever return error. You can call `f.t.Fatalf` like you do above, rather than returning error.

File: test/e2e/functional_test.go [hunk 3]
```diff
@@ -1237,3 +1240,51 @@ func (s *FunctionalSuite) TestControllerMetrics() {
...
+    metadata:
+      labels:
+        app: rollout-canary
+    spec:
+      containers:
+      - name: rollouts-demo
+        image: argoproj/rollouts-demo:blue
+        imagePullPolicy: Always
+        ports:
+        - containerPort: 8080
```
Comment (jessesuen) [inline test/e2e/functional_test.go:1267]: Can we use the nginx image like we do for the rest of the e2e tests? It will speed up tests since it should already be loaded into the kubernetes environment.

Also, `imagePullPolicy: Always` will slow down tests, and the container port for nginx is 80

**Review by jessesuen — APPROVED** [review]
LGTM. Please wait for e2e / unit tests to pass before merging (resubmit e2e as necessary due to flakiness)
