### PR TITLE
fix: Clear ProgressDeadlineExceeded Condition in paused BlueGreen Ro…

### LINKED ISSUE #939: ProgressDeadlineExceeded condition not cleared in a paused blueGreen rollout
## Summary 

When investigating a blueGreen rollout which was considered degraded because it had a ProgressDeadlineExceeded timeout condition, I noticed the pods were actually ready/available even though the condition was still set.

I think there may be a bug where the controller doesn't ever clear ProgressDeadlineExceeded once it reaches that condition.

## Diagnostics

What version of Argo Rollouts are you running? v0.10.2

---

**Message from the maintainers**:

Impacted by this bug? Give it a 👍. We prioritize the issues with the most 👍.

### PR DESCRIPTION
**Pull request by khhirani**
Closes #939 

Signed-off-by: khhirani <kareena.hirani@gmail.com>

### CODE REVIEW

File: test/e2e/bluegreen_test.go [hunk 1]
```diff
@@ -158,3 +158,121 @@ spec:
...
+		When().
+		ApplyManifests().
+		WaitForRolloutReplicas(2).
+		WaitForRolloutStatus("Healthy").
+		UpdateSpec().
+		WaitForRolloutStatus("Paused").
+		PromoteRollout().
+		WaitForRolloutStatus("Healthy").
+		Then().
+		ExpectActiveRevision("2")
```
Comment (jessesuen) [inline test/e2e/bluegreen_test.go:219]: Can the test be improved so that after UpdateSpec(), it waits for Degraded status and then Paused? We want to confirm it recovered from Degraded automatically.

File: test/e2e/bluegreen_test.go [hunk 2]
```diff
@@ -158,3 +158,121 @@ spec:
...
 		ExpectRevisionPods("revision 2 has active metadata2", "2", podsHaveActiveMetadata2)
 }
+
+func (s *BlueGreenSuite) TestBlueGreenProgressDeadlineExceededWithPause() {
+	s.Given().
+		RolloutObjects(`
+apiVersion: argoproj.io/v1alpha1
+kind: Rollout
+metadata:
+  name: rollout-bluegreen
```
Comment (jessesuen) [inline test/e2e/bluegreen_test.go:168]: Can we use a unique name for the rollout which is descriptive for the test? It helps with grepping controller logs during debugging

File: test/e2e/bluegreen_test.go [hunk 3]
```diff
@@ -158,3 +158,121 @@ spec:
...
+    matchLabels:
+      app: rollout-bluegreen
+  template:
+    metadata:
+      labels:
+        app: rollout-bluegreen
+    spec:
+      containers:
+      - name: rollouts-demo
+        image: argoproj/rollouts-demo:blue
```
Comment (jessesuen) [inline test/e2e/bluegreen_test.go:183]: Could we use the nginx image instead? All the other e2e tests use it and it helps with keeping the e2e tests running quicker since it does not need to pull images.

File: test/e2e/bluegreen_test.go [hunk 4]
```diff
@@ -158,3 +158,121 @@ spec:
...
+        imagePullPolicy: Always
```
Comment (jessesuen) [inline test/e2e/bluegreen_test.go:184]: remove `imagePullPolicy: Always` since it slows down tests.

File: test/e2e/bluegreen_test.go [hunk 5]
```diff
@@ -158,3 +158,121 @@ spec:
...
+        ports:
+        - containerPort: 8080
+        readinessProbe:
+          initialDelaySeconds: 20
```
Comment (jessesuen) [inline test/e2e/bluegreen_test.go:188]: Can we try: `progressDeadlineSeconds: 5` and `initialDelaySeconds: 10` to speed up the test?

File: test/e2e/bluegreen_test.go [hunk 6]
```diff
@@ -158,3 +158,121 @@ spec:
...
+
+func (s *BlueGreenSuite) TestBlueGreenProgressDeadlineExceededWithPause() {
+	s.Given().
+		RolloutObjects(`
+apiVersion: argoproj.io/v1alpha1
+kind: Rollout
+metadata:
+  name: rollout-bluegreen
+spec:
+  replicas: 2
```
Comment (jessesuen) [inline test/e2e/bluegreen_test.go:170]: Remove replicas so we only need to start 1 container, so we can speed up the test.

File: test/e2e/bluegreen_test.go (hunk 3 above)
Comment (khhirani) [reply test/e2e/bluegreen_test.go:183]: Is it possible for me to use a readiness probe when using the nginx image? I need to configure a readiness probe to set `initialDelaySeconds`.

Comment (jessesuen) [reply test/e2e/bluegreen_test.go]: Yes it just need to be modified to the port which nginx listens on instead of rollouts-demo

**Review by jessesuen — APPROVED** [review]
